spring:
  application:
    name: myvedio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.99.75.148:3306/myvideo

  datasource.hikari:
    maximum-pool-size: 10